// Generated by CoffeeScript 1.10.0
(function() {
  (angular.module('printMe', [])).directive('printMe', function($timeout, $window, PRINT_ME_CONSTANTS) {
    return {
      restrict: 'A',
      scope: false,
      controller: function($scope, $element) {
        this.print = $scope.print = function() {
          return $timeout(function() {
            $window.print();
            return $element.remove();
          });
        };
        return this;
      },
      link: function(scope, elem, attrs) {
        var appendStyles;
        elem.attr('id', 'print-area');
        if (attrs.printMe === 'trigger') {

        } else {
          scope.print();
        }
        appendStyles = function() {
          var styleTag;
          if ($window.document.getElementById(PRINT_ME_CONSTANTS.id)) {
            return;
          }
          styleTag = $window.document.createElement('style');
          styleTag.type = 'text/css';
          styleTag.id = PRINT_ME_CONSTANTS.id;
          if (styleTag.styleSheet) {
            styleTag.styleSheet.cssText = PRINT_ME_CONSTANTS.css;
          } else {
            styleTag.appendChild($window.document.createTextNode(PRINT_ME_CONSTANTS.css));
          }
          return $window.document.head.appendChild(styleTag);
        };
        return appendStyles();
      }
    };
  }).constant('PRINT_ME_CONSTANTS', {
    id: 'print-me-css',
    css: "@media screen {\n  #print-area {\n    display: none;\n  }\n}\n\n@media print {\n  body * {\n    visibility: hidden;\n  }\n\n  #print-area, #print-area * {\n    visibility: visible;\n  }\n\n  #print-area {\n    position: absolute;\n    left: 0;\n    top: 0.5in;\n  }\n}"
  });

}).call(this);
